spring:
  datasource:
    password: Test923#
    platform: mysql
    url: jdbc:mysql://localhost:3306/au
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  file:
    path: logs
          
    